package org.nha.project.core.reference

val INDIAN_STATE_NAMES: Map<String, String> =
    mapOf(
        "35" to "Andaman and Nicobar Islands",
        "28" to "Andhra Pradesh",
        "12" to "Arunachal Pradesh",
        "18" to "Assam",
        "10" to "Bihar",
        "4" to "Chandigarh",
        "22" to "Chhattisgarh",
        "7" to "Delhi",
        "30" to "Goa",
        "24" to "Gujarat",
        "6" to "Haryana",
        "2" to "Himachal Pradesh",
        "1" to "Jammu and Kashmir",
        "20" to "Jharkhand",
        "29" to "Karnataka",
        "32" to "Kerala",
        "37" to "Ladakh",
        "31" to "Lakshadweep",
        "23" to "Madhya Pradesh",
        "27" to "Maharashtra",
        "14" to "Manipur",
        "17" to "Meghalaya",
        "15" to "Mizoram",
        "13" to "Nagaland",
        "21" to "Odisha",
        "34" to "Puducherry",
        "3" to "Punjab",
        "8" to "Rajasthan",
        "11" to "Sikkim",
        "33" to "Tamil Nadu",
        "36" to "Telangana",
        "38" to "The Dadra and Nagar Haveli and Daman and Diu",
        "16" to "Tripura",
        "9" to "Uttar Pradesh",
        "5" to "Uttarakhand",
        "19" to "West Bengal",
    )
